#!/usr/bin/env bash
RED='\033[0;31m';
BLUE='\033[0;34m';
GREEN='\033[0;32m';
NC='\033[0m';

for i in *.pt
do
    echo -e "\n${BLUE}Testing file: ${NC}$i"
    ssltrace "ptc -L ../lib/pt -o1 -t1 $i" ../lib/pt/scan.def
done
